fancybox: true ## 是否启用Fancybox图片灯箱效果 true/false.
disqus: ## disqus用户名，为空则不使用
google_search: true ## 使用google搜索引擎, true/false.
baidu_search: ## 使用百度搜索引擎, true/false.
google_analytics: ## Google统计ID
baidu_analytics: ## 百度统计ID
show_category_count: true ## 如果你想显示侧边栏分类下的文章数量，请设置值为true
busuanzi: true ## 使用不蒜子统计文章访问量 true/false

## 头部菜单
menu: 
  - page: home
    directory: .
  - page: archive
    directory: archives/
  - page: about
    directory: about/
  - page: rss
    directory: atom.xml

## 侧边栏小工具设置: search, category, tag, recent_posts, links
widgets:
  - search
  - category
  - tag
  - recent_posts
  - links

## 侧边栏链接
links: 
  - title: 标题
    url: http://www.example.com

## 静态文件目录
js: js
css: css

## 主题版本
version: 0.0.1